server.port=8080

peer.id=leader
peer.role=leader

mqtt.broker=tcp://127.0.0.1:1883
ipfs.rpc=http://127.0.0.1:5001

cluster.quorum-remote=2

cluster.heartbeat-interval-ms=5000
cluster.heartbeat-initial-delay-ms=2000
cluster.leader-timeout-ms=15000